Adds an explainer document
w3c/distributed-tracing-wg pull request #40
Opened 2020-06-16 18:17 UTC by danielkhan

2020-06-16 19:04 UTC, subvocal requested changes
I really like the images as a way to explain what trace context is. Could you add the explainer_context_preserved.png image to the first paragraph that illustrates this scenario? Maybe make it clear in the image that Service A is instrumented by one tracing solution and Service B is instrumented by a different tracing solution?

2020-06-16 19:04 UTC, subvocal commented on EXPLAINER.md
> +- To provide a way in which heterogeneous architectures with multiple tracing platforms to operate in concert with each other
Suggest rewording to be more clear:
To provide a standard mechanism to propagate shared context across various architecture components so that multiple tracing platforms can be used in concert with each other.

2020-06-16 19:04 UTC, subvocal commented on EXPLAINER.md
> +- report back a new trace ID in case the callee, ignored the existing headers but started a new trace
remove the comma in

> callee, ignored

2020-06-16 19:04 UTC, subvocal commented on EXPLAINER.md
> +There are two common use cases. First is to define a context on trace initiation.
What's the second use case? Maybe put in a numbered list?

2020-06-16 19:04 UTC, subvocal commented on EXPLAINER.md
> +3. The API gateway operates standard compliant
Suggest rewording to:
The API gateway recognizes the headers as standards-compliant and allows them through

2020-06-17 14:11 UTC, dyladan commented on EXPLAINER.md
> +We propose a set of HTTP headers which propagate a distributed trace, even when a request and its associated trace is served by multiple tracing providers.
Baggage does not really fit into this description.
```suggestion
We propose a set of HTTP headers which propagate a distributed trace and associated data, even when a request and its associated trace is served by multiple tracing providers.
```

2020-06-29 20:38 UTC, danielkhan commented on EXPLAINER.md
> +There are two common use cases. First is to define a context on trace initiation.
I changed the whole section to contain a list of known use cases instead of randomly picking two

2020-06-29 20:38 UTC, danielkhan commented on EXPLAINER.md
> +3. The API gateway operates standard compliant
Done

2020-06-29 20:47 UTC, yurishkuro reviewed
Not really sure what the main objective of this document is, seems like a mix of different things.

2020-06-29 20:55 UTC, danielkhan commented
> Not really sure what the main objective of this document is, seems like a mix of different things.

We were asked to provide an explainer that covers what the working group is doing. This is more-or-less a companion doc to the charter.

2020-06-29 20:56 UTC, danielkhan commented
> I really like the images as a way to explain what trace context is. Could you add the explainer_context_preserved.png image to the first paragraph that illustrates this scenario? Maybe make it clear in the image that Service A is instrumented by one tracing solution and Service B is instrumented by a different tracing solution?

Added an end-to-end example image.

2020-06-29 21:46 UTC, danielkhan commented
I've incorporated all the requested changes. @mtwo, @SergeyKanzhelev, @victorNewRelic, @dyladan, @yurishkuro PTAL

2020-06-29 21:54 UTC, subvocal approved these changes

2020-06-29 21:54 UTC, yurishkuro approved these changes

2020-06-30 06:18 UTC, merged